---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - music.frsarker.kubebuilder.io
  resources:
  - songs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - music.frsarker.kubebuilder.io
  resources:
  - songs/finalizers
  verbs:
  - update
- apiGroups:
  - music.frsarker.kubebuilder.io
  resources:
  - songs/status
  verbs:
  - get
  - patch
  - update
